-- 创建一个单独的用户
CREATE USER IF NOT EXISTS 'lzb200244'@'%' IDENTIFIED BY 'lzb200244';
GRANT ALL PRIVILEGES ON *.* TO 'lzb200244'@'%';
-- 创建数据库
CREATE DATABASE IF NOT EXISTS select_course CHARACTER SET utf8mb4;
FLUSH PRIVILEGES;