# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
#  - job_name: 'prometheus' # 监控Prometheus
#    # 覆盖全局默认值，每15秒从该作业中刮取一次目标
#    scrape_interval: 15s
#    static_configs:
#      - targets: [ 'localhost:9090' ]
  - job_name: "course"
    scrape_interval: 15s
    static_configs:
      - targets: [ "192.168.1.6:20000" ]
  - job_name: "Go"
    scrape_interval: 15s
    static_configs:
      - targets: [ "192.168.1.6:8888" ]