apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: select-course
  labels:
    app: gateway
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      name: gateway
      labels:
        app: gateway
      annotations:
        kubesphere.io/imagepullsecrets: '{"user-service": "hw-secret"}'
    spec:
      volumes:
        - name: project-logs-volume
          hostPath:
            path: /data/select-course/logs
            type: DirectoryOrCreate
        - name: config-env
          configMap:
            name: config-env
            items:
              - key: .env
                path: .env
      containers:
        - name: gateway
          image: 'swr.cn-south-1.myhuaweicloud.com/lzb/select-course:latest'
          command:
            - /bin/sh
            - '-c'
            - export BASE_HOST=`hostname -i` && ./app
          ports:
            - containerPort: 8888
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: project-logs-volume
              mountPath: /project/logs
            - name: config-env
              mountPath: /project/.env
              subPath: .env
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: hw-secret
  strategy:
    rollingUpdate: # 滚动更新
      maxSurge: 25% # 滚动更新时，更新个数最多可以超过副本数的25%
      maxUnavailable: 25% # 滚动更新时，表示在所有副本数中多少个副本不可用
    type: RollingUpdate # 更新策略类型
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  namespace: select-course
  labels:
    app: gateway
    version: v1
spec:
  selector:
    app: gateway
  ports:
    - port: 8888
      targetPort: 8888

