---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: select-course
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: 'true'
spec:
  rules:
    - host: nginx.kubernetes-devops.cn
      http:
        paths:
          - pathType: Prefix
            path: "/api/v1/"
            backend:
              service:
                name: gateway-svc
                port:
                  number: 8888
