apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: select-course
  labels:
    app: user-service
    version: v1
spec:
  replicas: 2 # 副本数
  revisionHistoryLimit: 10 # 保留的最大历史版本
  # 更新策略
  strategy:
    rollingUpdate: # 滚动更新
      maxSurge: 25% # 滚动更新时，更新个数最多可以超过副本数的25%
      maxUnavailable: 25% # 滚动更新时，表示在所有副本数中多少个副本不可用
    type: RollingUpdate # 更新策略类型
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      name: user-service
      labels:
        app: user-service
      annotations:
        kubesphere.io/imagepullsecrets: '{"user-service": "hw-secret"}'
    spec:
      containers:
        - name: user-service
          image: swr.cn-south-1.myhuaweicloud.com/lzb/select-course:latest
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh", "-c", "export BASE_HOST=`hostname -i` && ./services/user/UserService" ]
          ports:
            - containerPort: 10000
              protocol: TCP
          volumeMounts:
            - name: config-env
              mountPath: /project/.env
              subPath: .env
            - name: project-logs-volume
              mountPath: /project/logs
      imagePullSecrets:
        - name: hw-secret
      volumes:
        - name: config-env
          configMap:
            name: config-env
            items:
              - key: .env
                path: .env
        - name: project-logs-volume
          hostPath:
            path: /data/logs
            type: DirectoryOrCreate
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: select-course
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 10000
      targetPort: 10000
      protocol: TCP
