name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Login docker
        run: |
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin swr.cn-south-1.myhuaweicloud.com

      - name: Build and push
        uses: docker/build-push-action@v4
        env:
          IMAGE_TAG: ${{ github.sha }}
        with:
          push: true
          tags: |
            swr.cn-south-1.myhuaweicloud.com/lzb/select-course:latest
            swr.cn-south-1.myhuaweicloud.com/lzb/select-course:${{ env.IMAGE_TAG }}
